CREATE USER IF NOT EXISTS 'DB_USER'@'DB_HOST' IDENTIFIED BY 'DB_PASSWORD';
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_USER'@'DB_HOST';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS DB_NAME;
USE DB_NAME;
CREATE TABLE IF NOT EXISTS DB_TABLE_USERS (
        username VARCHAR(255) PRIMARY KEY NOT NULL,
        password VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        total_wins INT DEFAULT 0,
        total_loss INT DEFAULT 0
);
CREATE TABLE IF NOT EXISTS DB_TABLE_EMAIL_VERIFICATION (
        email VARCHAR(255) NOT NULL PRIMARY KEY,
        code INT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS DB_TABLE_SESSION_TOKEN (
        session_token VARCHAR(255) PRIMARY KEY NOT NULL,
        username VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS DB_TABLE_PERSISTENT_TOKEN (
        persistent_token VARCHAR(255) PRIMARY KEY NOT NULL,
        username VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS DB_TABLE_GLOBAL_CHAT (
        id INT AUTO_INCREMENT PRIMARY KEY,
        time INT NOT NULL,
        sender VARCHAR(255) NOT NULL,
        message VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS DB_TABLE_ACTIVE_GAMES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gameId VARCHAR(255) NOT NULL UNIQUE,
    challenger VARCHAR(255) NOT NULL,
    challenged VARCHAR(255) NOT NULL,
    challengerColor VARCHAR(255) NOT NULL,
    challengedColor VARCHAR(255) NOT NULL,
    playerTurn VARCHAR(255) NOT NULL,
    capturedWhitePieces VARCHAR(255) NOT NULL,
    capturedBlackPieces VARCHAR(255) NOT NULL,
    boardStr TEXT NOT NULL
);
