export const BoardWhite = ({ onClickSquare }) => {
  return (
    <div className='board' id="board-white">
      <button className="square white-square" id="row-7-col-0" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-7-col-1" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-7-col-2" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-7-col-3" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-7-col-4" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-7-col-5" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-7-col-6" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-7-col-7" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-6-col-0" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-6-col-1" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-6-col-2" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-6-col-3" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-6-col-4" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-6-col-5" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-6-col-6" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-6-col-7" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-5-col-0" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-5-col-1" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-5-col-2" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-5-col-3" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-5-col-4" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-5-col-5" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-5-col-6" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-5-col-7" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-4-col-0" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-4-col-1" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-4-col-2" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-4-col-3" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-4-col-4" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-4-col-5" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-4-col-6" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-4-col-7" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-3-col-0" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-3-col-1" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-3-col-2" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-3-col-3" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-3-col-4" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-3-col-5" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-3-col-6" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-3-col-7" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-2-col-0" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-2-col-1" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-2-col-2" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-2-col-3" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-2-col-4" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-2-col-5" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-2-col-6" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-2-col-7" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-1-col-0" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-1-col-1" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-1-col-2" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-1-col-3" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-1-col-4" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-1-col-5" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-1-col-6" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-1-col-7" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-0-col-0" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-0-col-1" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-0-col-2" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-0-col-3" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-0-col-4" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-0-col-5" onClick={(event) => onClickSquare(event)}></button>
      <button className="square black-square" id="row-0-col-6" onClick={(event) => onClickSquare(event)}></button>
      <button className="square white-square" id="row-0-col-7" onClick={(event) => onClickSquare(event)}></button>
    </div>
  )
}
